### ISSUE TITLE
Update CI to Xcode 10

### ISSUE THREAD

**Issue by bachand** [airbnb/BuckSample#102]
I cannot merge my Siri Shortcut PR (https://github.com/airbnb/BuckSample/pull/86) until we update CI to Xcode 10 since Siri Shortcuts are a feature of Xcode 10.

**Comment by qyang-nj** [comment]
Travis CI's Xcode 10 machines don't have Java 8, which is required by Buck. (travis-ci/travis-ci#10307)

Not sure  if we can switch to another CI vendor.

**Comment by bachand** [comment]
Maybe CircleCI is worth looking into? They’re another big player in the space

**Comment by thedavidharris** [comment]
We use CircleCI for most of our iOS things, for open source projects they should give you 1x concurrency for free if you contact them (https://circleci.com/pricing/#faq-section-os-x), not sure if they hold you to the build limits of not.

https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-594/index.html shows that their recent images do still have Java 8; I checked and confirmed that too.

Feel free to reach out to me on Slack/Twitter/email/whatever, I could help some with this

**Comment by bachand** [comment]
This sounds promising. We met up last week and decided we're going to try CircleCI as our next step.

Thanks for investigating if they have Java 8 👍

**Comment by bachand** [comment]
(@shepting and @qyang-nj's team are owning this, so I will let them coordinate if they think there are parallelizable tasks 👌)

**Comment by thedavidharris** [comment]
The biggest issue we run into is that we saturate the available disk space on their images really easily. Might throw something in the Buck Slack to work on cache sizes. Should be fine for the example app though, as long as your cache is like < 10GB and/or you're not copying a bunch of built products to simulators in the same run it's enough

**Comment by bachand** [comment]
Ah I see. Should be enough for this repo, I hope.

**Comment by qyang-nj** [comment]
Fixed by #108
