### ISSUE TITLE
Issues with importing *-Swift.h in an apple_binary()

### ISSUE THREAD

**Issue by davidxiasc** [airbnb/BuckSample#107]
I'm trying to create an apple_binary() that contains swift code which will be called by Obj-C. It seems that I can't get the header to resolve. For background, I'm trying to convert a xcodeproj into a BUCK project. The xcode project has the following options defined:

 - Defines Module = Yes
 - Project Module Name = foo

So we have some Obj-C files that have the import

```objc
#import "foo-Swift.h"
```

But when building with buck, we are unable to resolve this header. Although this is similar to #5, its not totally the same as we are not building a library and ideally would rather not have the swift header prefix be the same as the target, since we have multiple targets which depend on the same objc file that makes this import.

Created a fork with commit: https://github.com/davidxiasc/BuckSample/commit/c811b9513f1c550a420ec2bf90130d607eb0f730 to demonstrate the issue.

Command run:

```
buck build //Libraries/SwiftAndObjc:SwiftAndObjcBinary
```

So far, I've tried adding the following swift compiler flags:

```
-emit-module -module-name foo
```

as this is what was generated by the output of `xcodebuild` when building the swift files. However, `-module-name foo` produces an additional error:

```
<unknown>:0: error: unknown argument: '-module-name foo'
```

Any guidance on how to resolve this would be much appreciated! 🙂

**Comment by dfed** [comment]
I haven't tried using these compiler flags, so I won't be much help on those. My questions are (assuming you remove the compiler flags):

1. Does `#import "SwiftAndObjcBinary-Swift.h"` work?
2. What fork/branch of `buck` are you using?
3. What is the downside of wrapping the binary code into a library and depending on it like we in https://github.com/airbnb/BuckSample/pull/44? I outlined the steps we took in https://github.com/airbnb/BuckSample/issues/24#issuecomment-468250837. Your "BinaryName-Swift.h" imports should work if you do that.

**Comment by qyang-nj** [comment]
I believe buck never supports mixed module for `apple_binary`. This PR (https://github.com/facebook/buck/pull/1875) added the mixed language support only for `apple_library`. 

There are two workaround for this problem:
1. have the `apple_binary` depend on a `apple_library`. This is what we are using in the BuckSample.
2. manually create a bridging header.

**Comment by davidxiasc** [comment]
Right our workaround for now will be creating the bridging header with the desired name manually, which simply imports the generated header. i.e.

foo-Swift.h looks like
```c
#import "FooBinary-Swift.h"
```

**Comment by davidxiasc** [comment]
following up - the hack I mentioned above was actually pretty painful since it worked on the command line but not in the project file.

What did work nicely was adding `module_name = 'foo'` to the `apple_binary` section
