### ISSUE TITLE
Running Buck with iOS 10

### ISSUE THREAD

**Issue by rockbruno** [airbnb/BuckSample#115]
Both in the sample and my real app, Buck apps fails to run in iOS 10 when installing in the simulator: (the sample's target is iOS 11, but I've reduced it to test this out)

```
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.airbnb.ExampleApp" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified.
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
	The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)
BUILD FAILED: Cannot launch //App:ExampleApp#dwarf-and-dsym,no-include-frameworks (failed to launch bundle ID com.airbnb.ExampleApp)
```

The app itself gets installed after this, but trying to run it results in a crash at the splash screen.   I was unable to retrieve a log for the sample app, but in my real app this crash happens inside UIKit: `[UIView(AdditionalLayoutSupport) nsli_lowerAttribute:intoExpression:withCoefficient:forConstraint:onBehalfOfLayoutGuide:]`

Is this something that you guys have dealt with before in your production app?

**Comment by rockbruno** [comment]
This seemed to be a problem with the iPhone 5 simulator. Using iPhone 5s works.

**Comment by qyang-nj** [comment]
The minimum iOS version we support is 11, so we didn't see this problem.

**Comment by dfed** [comment]
@rockbruno could this be an issue between 32bit vs 64bit? `iPhone 5` is 32bit, `iPhone 5s` is 64bit. Check out [this link](https://blakespot.com/ios_device_specifications_grid.html) for a(n impressively) comprehensive list.

**Comment by rockbruno** [comment]
That was it @dfed ! Compiling for `#iphonesimulator-i386` did the trick :) Thanks!

**Comment by dfed** [comment]
Woot! I've updated the title to better reflect the underlying issue. Hopefully that'll help the next person 🙂
