### ISSUE TITLE
Question about Embedded Binaries (Carthage frameworks) in generated Xcode workspace

### ISSUE THREAD

**Issue by BlakeRxxk** [airbnb/BuckSample#118]
all `prebuilt_apple_framework` in generated via buck Xcode workspace goes as `Embedded Binaries` and also in `Copy Files` in `Build Phase`, for example FirebaseAnalytics.

So it leads to some building/running issues and bad developer experience while working with generated project.

Is there any chance to exclude this frameworks from generated `Copy Files`?

**Comment by qyang-nj** [comment]
Hi @BlakeRxxk, I guess you don't want the the frameworks to be embedded because that are statically linked (otherwise they should be embedded). In this case, we just use `prebuilt_cxx_library`.

**Comment by BlakeRxxk** [comment]
@qyang-nj yep, this is what I looking for, thank you. I'll try `prebuilt_cxx_library`

maybe we should add example for this case?
