### ISSUE TITLE
Import Realm pod

### ISSUE THREAD

**Issue by gsabran** [airbnb/BuckSample#14]
Hi, thanks for this great sample app! I've tried to use if with Realm:

```
# Podfile
pod 'RealmSwift'
```
```
# Pods/BUCK

apple_pod_lib(
    name = "Realm",
    visibility = ["PUBLIC"],
    exported_headers = glob([
        "Realm/**/*.h",
        "Realm/**/*.hpp",
    ]),
    srcs = glob([
        "Realm/**/*.m",
        "Realm/**/*.mm",
        "Realm/**/*.cpp",
    ]),
)

apple_pod_lib(
    name = "RealmSwift",
    visibility = ["PUBLIC"],
    swift_version = "4.2",
    srcs = glob([
        "RealmSwift/**/*.swift",
    ]),
    deps = [
        "//Pods:Realm"
    ],
)

```

But then when building my project I get the error:
```
In target '//Pods:Realm', 'Realm/history.hpp' maps to the following header files:
- .../BuckSample/Pods/Realm/include/core/realm/sync/history.hpp
- .../BuckSample/Pods/Realm/include/core/realm/history.hpp

Please rename one of them or export one of them to a different path.
```

What is the best way to deal with this?

**Comment by dfed** [comment]
Looks like this question was answered here https://github.com/facebook/buck/issues/2159

@gsabran, if you're interested in submitting a PR to this project that imports Realm and shows how to path/name re-mapping, know that we'd welcome it.

**Comment by gsabran** [comment]
I'd love to. I'm not there yet :)

**Comment by gsabran** [comment]
Installing the prebuilt framework through Carthage and using something like [SwiftWithPrecompiledDependency](https://github.com/airbnb/BuckSample/tree/master/Libraries/SwiftWithPrecompiledDependency) works. Not sure about how to do this through Cocoapods.

**Comment by dfed** [comment]
I think there's benefit in trying to get an example of path remapping on a third-party library pod. But this isn't a high-priority item on our to-do list, and it is indeed good that there's a workaround. I'm happy to leave this closed.
