### ISSUE TITLE
.ipa path

### ISSUE THREAD

**Issue by hakanyildizay** [airbnb/BuckSample#2]
Hi everybody,
I am trying to export ipa file.

Here is .buckconfig
`[cxx]
  default_platform = iphonesimulator-x86_64
  cflags = -g -fmodules -fobjc-arc -D BUCK -w
  combined_preprocess_and_compile = true

[swift]
  version = 3.2
  compiler_flags = -DBUCK -whole-module-optimization -enable-testing -suppress-warnings
`

And BUCK file

`apple_resource(
    name = 'AppResources',
    dirs = [],
    files = glob(['**/*.xib','**/*.storyboard']),
)

apple_asset_catalog(
  name = 'AppAsset',
  dirs = ['SampleApp/Assets.xcassets'],
)

apple_binary(
    name = 'AppBinary',
    srcs = glob([
        'SampleApp/*.swift',
      ]),
    deps = [':AppResources', ':AppAsset'],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    ],
)

apple_bundle(
    name = 'TheApp',
    binary = ':AppBinary',
    extension = 'app',
    info_plist = 'SampleApp/Info.plist',
    info_plist_substitutions = {
        'PRODUCT_BUNDLE_IDENTIFIER': 'com.some.bundleID',
        'CURRENT_PROJECT_VERSION': '1',
        'DEVELOPMENT_LANGUAGE': 'Base',
    },
)

apple_package(
  name = 'SampleAppPackage',
  bundle = ':TheApp',
)
`

I don't know what to pass to apple_package() or apple_bundle() functions. 
In configuration file I couldn't find .ipa export or archive path.
  
I would really appreciate if you could help me.
Thank you.

**Comment by zayhero** [comment]
This config looks fine, if you run `buck build //:SampleAppPackage`, you should able to find the `.ipa` file in `buck-out/gen/SampleAppPackage`
