### ISSUE TITLE
Error build on Xcode `make project`

### ISSUE THREAD

**Issue by hendych** [airbnb/BuckSample#22]
# Reproduce Method
1. Clone git.
2. Run command `make project`
3. Xcode opened, then run `cmd + B` or build.
4. Build failed.

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "SwiftAndObjc.h"
        ^
/<your env dir>/_p/1YWHeOsVjJ-pub/SwiftAndObjc/SwiftAndObjc.h:2:9: error: 'SwiftAndObjc/SwiftAndObjc-Swift.h' file not found
#import <SwiftAndObjc/SwiftAndObjc-Swift.h>
        ^
<unknown>:0: error: could not build Objective-C module 'SwiftAndObjc'
```

# Xcode Version
`10.1`

**Comment by dfed** [comment]
You’re building on latest master? I bumped the `buck` version the `Makefile` used yesterday to fix this.

**Comment by mgrebenets** [comment]
@dfed I think README says `brew install buck`, while the correct command seems to be `make install_buck`.

**Comment by dfed** [comment]
Ahhh good find. Fixing.
