### ISSUE TITLE
Issues when running make test command

### ISSUE THREAD

**Issue by mgrebenets** [airbnb/BuckSample#23]
While running `make test` command I get errors like this:

```
ERROR: /Users/grebenma/dev/oss/buck-samples/airbnb/BuckSample/tools/buck:2:3: invalid character: ''
ERROR: /Users/grebenma/dev/oss/buck-samples/airbnb/BuckSample/tools/buck:2:4: invalid character: ''
ERROR: /Users/grebenma/dev/oss/buck-samples/airbnb/BuckSample/tools/buck:2:5: invalid character: ''
```

Looks like it tries to treat the whole `tools/buck` executable as a huge string.
I used this command to capture output `make test 2>&1 | tee build.log`

Running `tools/buck test //App/Tests:Tests --all --exclude ui --test-runner-env FOO=BAR`  directly from command line causes same issue.

Running `./tools/buck build //App:ExampleAppBundle`, however, works just fine, as well as `make build`.
`tools/buck build //App/Tests:Tests` also works fine.

**Comment by dfed** [comment]
Whoops. Fix incoming.
