### ISSUE TITLE
Can't build project after installing Java JDK

### ISSUE THREAD

**Issue by bachand** [airbnb/BuckSample#60]
I cloned the project, ran `make install_buck`, and then ran `make build`.

```
tools/buck build //App:ExampleAppBundle
Not using buckd because watchman isn't installed.
No Java runtime present, requesting install.
Cannot verify that installed Java version at '/usr/bin/java' is correct.
make: *** [build] Error 1
```

I also got this popup.
<img width="532" alt="Screen Shot 2019-03-21 at 12 41 40 AM" src="https://user-images.githubusercontent.com/1791049/54738594-1a3bea80-4b72-11e9-9bc5-ce28fb8dcf83.png">

I clicked "More Info..." and was redirected [here](https://www.java.com/en/download/mac_download.jsp).

I downloaded and installed the JDK linked to from that page.

I then closed my shell and ran `make build` again. The same text was printed to the console and the popup appeared again.

**Comment by bachand** [comment]
I installed the "Mac OS X x64" version of the JDK from [here](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and that worked.

**Comment by dfed** [comment]
I found this solution helpful last night – I'll add a quick PR to the README to mention this install step
