### ISSUE TITLE
Add `UnitTestsWithHostApp` target so as to show examples of all test types

### ISSUE THREAD

**Issue by bachand** [airbnb/BuckSample#69]
As far as we know, Buck does not support UI tests cc: @dfed @qyang-nj .

Right now we have a target named `UITests`. In reality it sounds like this may be `UnitTestsWithHostedApp`.

I wonder if we should rename our test targets to be more clear. As a strawman, what if we did the following rename?

`:Tests` => `:UnitTests`
`:UITests` => `:UnitTestsWithHostedApp`

**Comment by dfed** [comment]
If we rename `:UITests` => `:UnitTestsWithHostedApp`, we should remove the `XCUIApplication().launch()` line from our `UITests` target. Since that is the line that actually makes our `UITests` target a `XCUITest` (as far as I can tell).

Fwiw, I do think we should do both of these things per https://github.com/airbnb/BuckSample/pull/64#discussion_r272444327

**Comment by qyang-nj** [comment]
I like this naming a lot. Just one thing, it should be `WithHostApp`, not `Hosted`. The app hosts the tests, not the other way around.

**Comment by dfed** [comment]
Per https://github.com/airbnb/BuckSample/pull/70, I no longer think we need the naming changes.

**Comment by bachand** [comment]
Wow nice!

I find the distinctions between these many types of tests very confusing.

I wonder if we should consider adding a third test target now: `UnitTestsWithHostApp`?

Then `BuckSample` could demo all of the different types of tests that you can run.

Even better we could add a comment above each test explaining why you would want to use one vs the other.

If you like that idea @dfed and @qyang-nj I can close this issue and open another that is more descriptive based on this new information.

**Comment by dfed** [comment]
> I wonder if we should consider adding a third test target now: UnitTestsWithHostApp

Absolutely. I like this idea!

> If you like that idea @dfed and @qyang-nj I can close this issue and open another that is more descriptive based on this new information.

I’m happy to repurpose this issue rather than creating a new one

**Comment by bachand** [comment]
Cool I updated the title.

If we do this we should probably rename the existing tests target to be `UnitTests`

**Comment by dfed** [comment]
@bachand see #71 😉

**Comment by bachand** [comment]
Hurray!
