### ISSUE TITLE
Run script phase when running make install

### ISSUE THREAD

**Issue by pkrmf** [airbnb/BuckSample#77]
Would it be possible to include an example on your sample project that runs make install and it executes a build phase run script?

I am trying to figure out the best way to execute a run script during make install or make build, but I don’t seem to find anytjing good out there.

**Comment by dfed** [comment]
I think you're looking for a [genrule](https://buckbuild.com/rule/genrule.html). We have a [couple](https://github.com/airbnb/BuckSample/blob/0a4a4d2919b05ba74da4791def260174556a06c0/Config/buck_rule_macros.bzl#L275) [examples](https://github.com/airbnb/BuckSample/blob/0a4a4d2919b05ba74da4791def260174556a06c0/Config/buck_rule_macros.bzl#L284) of using `genrule`s to execute scripts. These `genrule`s execute during `buck project`, `buck build`, and `buck test`.

We also have a Xcode-specific [prebuild](https://github.com/airbnb/BuckSample/blob/0a4a4d2919b05ba74da4791def260174556a06c0/App/BUCK#L90) and [postbuild](https://github.com/airbnb/BuckSample/blob/0a4a4d2919b05ba74da4791def260174556a06c0/App/BUCK#L100) script examples. Though these only run during Xcode builds, not during `buck` commands.

I'm closing this issue, as I think we already have what you're looking for. Please let me know if I've misunderstood!
