### ISSUE TITLE
[Feature Request] Support for Codegen tasks

### ISSUE THREAD

**Issue by mgrebenets** [airbnb/BuckSample#89]
Hi.

This feature request is about adding support for code generation tasks.
Code generation (codegen) tasks are quite common these days.
Once such example is using https://github.com/SwiftGen/SwiftGen to generate Swift code for images, assets or storyboards used in the app.

The thing with codegen tasks, is that they run _before_ the actual build.
In case of Xcode, codegen tasks would be added as custom build phases to be ran before "Compile Sources" build phase.

The feature request / question is how should codegen be done when it comes to Buck?

AFAIK, but rules don't ever write things back to the repo itself (unless ugly workarounds are used). We are using such ugly workaround where `genrule` is running a shell script and that shell script writes directly into `ROOT_REPO/...` path(s) where `ROOT_REPO` is another ugly thing we did as `REPO_ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))`.

Moving towards Starlark, we can't do things like `__file__` and such.

**Comment by bachand** [comment]
Here’s the options I see:

- If you don’t care about committing the generated code you can use a `genrule`.
- If you do care about committing the generated code I would recommend asking users to run a command (at Airbnb we use `rake`) when they need to generate code. That way it’s decoupled from Buck.

If your development workflow is such that you mostly work in Xcode (and build in Xcode) and only use Buck CLI for CI builds you could include the code generation in an `xcode_prebuild_script`.

Hope that helps.

**Comment by bachand** [comment]
We tried a workaround approach like what you suggested and moved away from it.

**Comment by mgrebenets** [comment]
Got it, makes a lot of sense now.

We will decouple codegen task(s) from Buck builds then, since we do care about committing generated code.

It's just that I've spend some time already to make codegen part of buck before I realised it doesn't quite fit with it.

We use quite a mix of scripts at the moment, but looks like in our case having a Fastlane lane doing the codegen part is the right call, similar to `rake` approach you describe.

**Comment by bachand** [comment]
Yeah it’s a bit of a bummer but I think this is one of the prices you pay for fast builds, at least without changing Buck 🤷‍♂️
