### ISSUE TITLE
ExampleApp crashes on launch after running `make debug`

### ISSUE THREAD

**Issue by bachand** [airbnb/BuckSample#91]
https://github.com/airbnb/BuckSample/pull/90 makes it possible for `make debug` to launch the `ExampleApp` in the simulator.

The app crashes on launch.

The app runs fine with Xcode.

I looked in Console.app and this looked suspicious.

<img width="1690" alt="Screen Shot 2019-04-27 at 12 45 00 PM" src="https://user-images.githubusercontent.com/1791049/56854403-eda28d80-68ea-11e9-89db-30d8c3179341.png">

**Comment by qyang-nj** [comment]
This is duplicated with #76. The latest Buck fixed this problem, but we couldn't merge it because our CI is still using Xcode 9. See #81 for the detail.
A quick fix is to set `ldflags = /usr/lib/swift` in `.buckconfig`, but I'd like to avoid it if possible.

**Comment by bachand** [comment]
Got it. I’ll close this.

I agree let’s not merge that fix.

I looked through our issues. What’s the next step here? Seems like our debt is accumulating 😬

(Also no need to figure out next steps this weekend.)
