### ISSUE TITLE
Unable to run `ExampleWatchApp` from Buck-generated Xcode project

### ISSUE THREAD

**Issue by bachand** [airbnb/BuckSample#97]
### Steps
1. `make project`.
2. Create a scheme for `ExampleWatchApp#watchsimulator-i386`.
3. Build and run.

### Result
Both the iPhone and Watch simulators open. The app is not installed on the watch. 

### Other attempts

- I tried explicitly installing `ExampleWatchApp` via the Watch app on the iPhone simulator.
- I tried creating a scheme for `ExampleWatchAppExtension#watchsimulator-i386` instead and then building and running.

Neither of these worked.

**Comment by bachand** [comment]
cc: @qyang-nj who has the most knowledge about the watch.

**Comment by qyang-nj** [comment]
Fixed by #100
